### ISSUE TITLE
OLED Tools Build Error

### ISSUE THREAD

**Issue by A4EVA** [lazywalker/devtools-feeds#1]
Hello, if I try to build the code I got the following error:

No roule to build target

Any idea ?

**Comment by lazywalker** [comment]
hi, try to follow the steps https://github.com/lazywalker/devtools-feeds/blob/master/README.md
when entering `make manuconfig` , ensure that you do select the right packages from `Dev Tools catagory` and properly save the config

**Comment by A4EVA** [comment]
Hi, I found the problem ! In the readme you mentioned to issue this command: `make package/oledtools/compile V=sc` But in the makefile the name of the package is different ! It is acually oled-tool so the correct build command is : 
`make package/oled-tools/compile V=sc` and it working fine package built correctly ! I also tried to build libardupioled but it fail to apply the first patch called 001-makefile.patch can you please check this ?

**Comment by lazywalker** [comment]
Oh it was a typo, i have updated the intro here, with libaruipioled as well
https://github.com/lazywalker/devtools-feeds/blob/master/README.md

**Comment by A4EVA** [comment]
I figured that out myself even for libaruipioled but if you try to make it it stops because as I already described the apply of 001-makefile.patch fail at hunk #1. Can you please check it ?

**Comment by lazywalker** [comment]
i did try it few hours ago without any problem, can you paste the detail or errors so i'll check it

**Comment by A4EVA** [comment]
My Fault, I've forgot to update the repo. Everything built perfectly Thank you so much !

**Comment by A4EVA** [comment]
the package oled-tool works perfectly and writes correctly to the screen but the oled_demo that come with libaruipioled shows an error when is executed : 
`root@OpenWrt:~# oled_demo -o 3 -v
oled_demo v1.1
-- OLED params --
Oled is    : Adafruit I2C 128x64
-- Other Stuff --
verbose is : yes

bcm2835_init: Unable to open /dev/mem: No such file or directory
`
are you aware of this error ? do I need to do something to have it working ?

**Comment by lazywalker** [comment]
> the package oled-tool works perfectly and writes correctly to the screen but the oled_demo that come with libaruipioled shows an error when is executed :
> `root@OpenWrt:~# oled_demo -o 3 -v
> oled_demo v1.1
> -- OLED params --
> Oled is : Adafruit I2C 128x64
> -- Other Stuff --
> verbose is : yes
> 
> bcm2835_init: Unable to open /dev/mem: No such file or directory
> `
> are you aware of this error ? do I need to do something to have it working ?

You can ignore the oled_demo comes with libaruipioled , the purpose of libaruipioled is to meet the need of mmdvmhost with OLED feature (https://github.com/lazywalker/mmdvm-openwrt/tree/OLED) , it works but the refreshing rate is slow with mmdvmhost, so it's a unfinished job, i hope someone have free time can finish it.

**Comment by A4EVA** [comment]
I'm giving it a try, I'll have you updated about that. Thank you for your help
